vkrS/vkrS/Models/Image.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Runtime.Serialization;
using System.Web;

namespace vkrS.Models
{
    [DataContract]
    public class Image
    {
        [Required]
        [DataMember]
        public Guid ImageId { get; set; }
        
        [DataMember]
        public string Description { get; set; }

        [Required]
        [DataMember]
        public string Link { get; set; }

        [ForeignKey("ImageId")]
        public virtual List<Result> Results { get; set; }
    }
}

vkrS/vkrS/Controllers/ImageController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using vkrS.Models;
using System.Data.Entity;

namespace vkrS.Controllers
{
    public class ImageController : Controller
    {
        private VKRDbContext db = new VKRDbContext();

        // GET: Image
        public ActionResult GetImages()
        {
            var images = db.Images;
            ViewBag.Images = images;
            return View();
        }

        [HttpPost]
        public void AddImage(string imageInput, string description)
        {
            if (imageInput != null)
            {
                db.Images.Add(new Image { ImageId = Guid.NewGuid(), Link = imageInput });
                db.SaveChanges();
            }
        }
    }
}

vkrS/vkrS/Controllers/OpenImageController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using vkrS.Models;

namespace vkrS.Controllers
{
    public class OpenImageController : Controller
    {
        private VKRDbContext db = new VKRDbContext();

        // GET: OpenImage
        public ActionResult GetOpenImage(Guid id)
        {
            var image = db.Images.FirstOrDefault(i => i.ImageId == id);
            if (image != null)
            {
                ViewBag.Link = image.Link;
                ViewBag.Id = image.ImageId;
                ViewBag.TimeSeries = db.TimeSeries;
                ViewBag.res = db.Results;
            }
            return View();
        }

        [HttpGet]
        public ActionResult Start(string imageInput, string ts)
        {
            if (imageInput != null && ts != null)
            {
                int total = (int)GC.GetTotalMemory(true);
                Guid imId = Guid.Parse(imageInput);
                Guid tsId = Guid.Parse(ts);
                var image = db.Images.FirstOrDefault(i => i.ImageId == imId);
                var timeseries = db.TimeSeries.FirstOrDefault(t => t.TimeSeriesId == tsId);
                if (image != null && timeseries != null)
                {
                    var startTime = System.Diagnostics.Stopwatch.StartNew();
                    Process process = new Process
                    {
                        StartInfo = new ProcessStartInfo
                        {
                            FileName = "cmd.exe",
                            RedirectStandardInput = true,
                            RedirectStandardOutput = true,
                            UseShellExecute = false,
                            Arguments = "/c docker pull " + image.Link
                        }
                    };

                    //process.Start();
                    //process.WaitForExit();

                    float cpu;
                    string result;
                    using (PerformanceCounter pcProcess = new PerformanceCounter("Process", "% Processor Time", "_Total"))
                    {
                        cpu = pcProcess.NextValue();

                        int indexOfChar = image.Link.IndexOf('/') + 1;
                        string im = image.Link.Remove(0, indexOfChar);
                        process.StartInfo = new ProcessStartInfo
                        {
                            FileName = "cmd.exe",
                            RedirectStandardInput = true,
                            RedirectStandardOutput = true,
                            UseShellExecute = false,
                            Arguments = "/c docker run -e ARRAY=" + timeseries.Elements.Replace(Environment.NewLine, "") + " " + im
                        };
                        process.Start();
                        StreamReader srIncoming = process.StandardOutput;

                        result = srIncoming.ReadToEnd();
                        startTime.Stop();
                        process.WaitForExit();
                        cpu = pcProcess.NextValue() / (float)Environment.ProcessorCount;
                    }

                    var c = (int)cpu;

                    process.Close();
                    var resultTime = startTime.Elapsed;

                    total = (int)GC.GetTotalMemory(true) - total;

                    total = ((int)(total / (float)Environment.ProcessorCount))/1024;
                    
                    var res = new Result { ResultId = Guid.NewGuid(), ImageId = image.ImageId, TimeSeriesId = timeseries.TimeSeriesId, Res = result, Time = resultTime , Memory=total.ToString(), CPU=c+"%"};
                    db.Results.Add(res);
                    db.SaveChanges();
                    return Redirect("~/Result/GetResult/" + res.ResultId);
                }
            }
            return Content("error");
        }
    }
}

vkrS/vkrS/Controllers/StatisticController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using vkrS.Models;
using System.Data.Entity;

namespace vkrS.Controllers
{
    public class StatisticController : Controller
    {
        private VKRDbContext db = new VKRDbContext();

        // GET: Statistic
        public ActionResult GetStatistic()
        {
            ViewBag.Results = db.Results.Include(r=>r.Image);
            ViewBag.TS = db.TimeSeries.Where(t=>t.Results.Count>0).OrderByDescending(t=>t.Results.Count);
            return View();
        }
    }
}

vkrS/vkrS/Views/Image/GetImages.cshtml
<script src="https://ajax.googleapis.com/ajax/libs/jquery/2.2.0/jquery.min.js"></script>
@Styles.Render("~/Content/css")

<h2 class="h3">Методы</h2>

@Html.ActionLink("Статистика", "GetStatistic", "Statistic", null, new { area = "", @class = "btn-default" })

<div class="table-responsive table-hover" id="">
    <table class="table table-striped">
        <thead>
            <tr>
                <th>Название</th>
                <th>Описание</th>
                @*<th>Среднее качество</th>возвращать среднюю оценку всех результатов по этому методу*@
            </tr>
        </thead>
        <tbody>
            @foreach (var i in ViewBag.Images)
            {

                <tr>
                    <th>@i.Link</th>
                    <th>@i.Description</th>
                    <th class=""> @Html.ActionLink("Перейти", "GetOpenImage", "OpenImage", new { id = i.ImageId.ToString() }, new { area = "", @class = "btn-default" })</th>
                </tr>
            }
        </tbody>
    </table>
</div>

<h2 class="h3">Добавление метода</h2>
<div class="row">
    <div class="col-sm-10">
        <input id="imageInput" type="text" class="form-control" placeholder="user/image" />
        <textarea type="text" id="description" class="form-control" placeholder="Описание" rows="3" style="resize:none;margin-top:0.5rem"></textarea>
        <input type="button" value="Добавить метод" class="btn btn-sm btn-primary" style="margin-top:0.5rem" onclick="AddImage()" />
    </div>
</div>

<script type="text/javascript">
    $(document).ready(function () {

    });

    function AddImage() {
        $.ajax({
            url: '@Url.Action("AddImage")',
            type: 'POST',
            data: JSON.stringify({ 'imageInput': $("#imageInput").val(), 'description': $("#description").val() }),
            contentType: "application/json;charset=utf-8",
            success: function (data) {
                $("#imageInput").val('');
                $("#description").val('');
            },
            error: function () {
                alert('error');
            }
        });
    }
</script>