vkrS/vkrS/Controllers/TimeSeriesController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using System.Web;
using System.Web.Http.Description;
using System.Web.Mvc;
using Newtonsoft.Json;
using vkrS.Models;

namespace vkrS.Controllers
{
    public class TimeSeriesController : Controller
    {
        private VKRDbContext db = new VKRDbContext();

        // GET: TimeSeries
        public JsonResult GetTimeSeries()
        {
            return Json(db.TimeSeries, JsonRequestBehavior.AllowGet);
        }

        public ActionResult GetTimeSeriesAdmin()
        {
            var ts = db.TimeSeries;
            ViewBag.TimeSeries = ts;
            ViewBag.TimeSeriesCount = db.TimeSeries.Count();
            return View();
        }

        [HttpPost]
        public ActionResult AddTimeSeries(HttpPostedFileBase fileInput, string title, string description)
        {
            if (fileInput == null) return null;
            int c = 0;
            string elements = "";
            using (StreamReader sr = new StreamReader(fileInput.InputStream))
            {
                string l = "";
                while ((l = sr.ReadLine()) != null)
                {
                    c++;
                    elements += l;

                }
            }
            int[] arr = new int[c];
            for (int i = 0; i < c; i++)
            {
                arr[i] = Convert.ToInt32(elements[i]);
            }
            var el = elements;
            elements = elements.Replace(Environment.NewLine, "");
            if (title == string.Empty) title = fileInput.FileName;
            if (description == string.Empty) description = "";
            var ts = new TimeSeries { TimeSeriesId = Guid.NewGuid(), AmountOfElements = c, Title = title, Elements = elements, Description = description };
            db.TimeSeries.Add(ts);
            db.SaveChanges();
            ViewBag.Title = title;

            var chartData = new StringBuilder();
            chartData.Append("[");
            for (int i = 0; i < c; i++)
            {
                if (i == ts.AmountOfElements - 1)
                {
                    chartData.Append(string.Format("{0}", ts.Elements[i]));
                    break;
                }
                chartData.Append(string.Format("{0},", elements[i]));
            }
            chartData.Append("]");
            ViewBag.chartData = chartData;
            ViewBag.Title = ts.Title;

            return View("TimeSeriesVisual");
        }

        public ActionResult VisualTimeSeries(string id)
        {
            var idts = Guid.Parse(id);
            var ts = db.TimeSeries.FirstOrDefault(t => t.TimeSeriesId == idts);

            var chartData = new StringBuilder();
            chartData.Append("[");
            for (int i = 0; i < ts.AmountOfElements; i++)
            {
                if(i== ts.AmountOfElements - 1)
                {
                    chartData.Append(string.Format("{0}", ts.Elements[i]));
                    break;
                }
                chartData.Append(string.Format("{0},", ts.Elements[i]));
            }
            chartData.Append("]");
            ViewBag.chartData = chartData;
            ViewBag.Title = ts.Title;

            return View("TimeSeriesVisual");
        }
    }
}

vkrS/vkrS/Views/TimeSeries/GetTimeSeriesAdmin.cshtml
<script src="https://ajax.googleapis.com/ajax/libs/jquery/2.2.0/jquery.min.js"></script>
@{
    ViewBag.Title = "GetTimeSeriesAdmin";
}
<h2 class="h3">Временные ряды</h2>
<div class="table-responsive" id="">
    <table class="table table-striped">
        <thead>
            <tr>
                <th>Название</th>
                <th>Количество элементов</th>
                <th>Описание</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var t in ViewBag.TimeSeries)
            {
                <tr>
                    <th>@t.Title</th>
                    <th>@t.AmountOfElements</th>
                    <th>@t.Description</th>
                    <th>@Html.ActionLink("Посмотреть", "VisualTimeSeries", "TimeSeries", new { id = t.TimeSeriesId }, new { area = "", @class = "btn-default" })</th>
                </tr>
            }
        </tbody>
    </table>
</div>

@using (Html.BeginForm("AddTimeSeries", "TimeSeries", FormMethod.Post, new { @enctype = "multipart/form-data" }))
{
<h2 class="h3">Добавление ряда</h2>
    <div class="row">
        <div class="col-sm-10">
                <input type="file" id="fileInput" name="fileInput" value="Добавить файл" />
            <input type="text" id="title" name="title" class="form-control" placeholder="Название" style="margin-top:0.5rem" />
            <textarea type="text" id="description" name="description" class="form-control" placeholder="Описание" rows="3" style="resize:none;margin-top:0.5rem"></textarea>
            <input type="submit" value="Загрузить" class="btn btn-sm btn-primary" style="margin-top:0.5rem" onclick="AddTS()" />
        </div>
    </div>

}


<script type="text/javascript">
    var id;
    $(document).ready(function () {

    });
    

</script>

vkrS/vkrS/Views/TimeSeries/TimeSeriesVisual.cshtml
<script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.7.1/Chart.min.js"></script>
<script src="https://code.highcharts.com/highcharts.js"></script>
<script src="https://code.highcharts.com/modules/data.js"></script>
<script src="https://code.highcharts.com/modules/exporting.js"></script>
<script src="https://code.highcharts.com/modules/export-data.js"></script>
<script src="https://code.highcharts.com/modules/accessibility.js"></script>


<h2>@ViewBag.Title</h2>
<div id="container"></div>

<script type="text/javascript">
        var canvas = document.getElementById("canvas");

    Highcharts.chart('container', {
        chart: {
            zoomType: 'x'
        },
        title: {
            text: ''
        },
        subtitle: {
            text: document.ontouchstart === undefined ?
                'Click and drag in the plot area to zoom in' : 'Pinch the chart to zoom in'
        },
        xAxis: {
            title: {
                text: 'Элементы'
            }
        },
        yAxis: {
            visible:false
        },
        legend: {
            enabled: false
        },
        plotOptions: {
            area: {
                fillColor: {
                    linearGradient: {
                        x1: 0,
                        y1: 0,
                        x2: 0,
                        y2: 1
                    },
                    stops: [
                        [0, Highcharts.getOptions().colors[0]],
                        [1, Highcharts.color(Highcharts.getOptions().colors[0]).setOpacity(0).get('rgba')]
                    ]
                },
                marker: {
                    radius: 2
                },
                lineWidth: 1,
                states: {
                    hover: {
                        lineWidth: 1
                    }
                },
                threshold: null
            }
        },

        series: [{
            type: 'area',
            data: @ViewBag.chartData
        }]
    });


</script>