vkrS/vkrS/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using vkrS.Models;

namespace vkrS.Controllers
{
    public class HomeController : Controller
    {
        private VKRDbContext db = new VKRDbContext();

        public ActionResult Index()
        {
            ViewBag.Title = "Home Page";
            SelectList images = new SelectList(db.Images, "ImageId", "Link");
            ViewBag.Images = images;
            SelectList ts = new SelectList(db.TimeSeries, "TimeSeriesId", "Elements");
            ViewBag.TimeSeries = ts;

            return View();
        }

        [HttpPost]
        public ActionResult Login(string login, string password)
        {
            var user = db.Users.FirstOrDefault(u => u.Login == login && u.Password == password);
            if (user == null)
            {
                return Json(new { status = "error", message = "no user" });
            }
            user.IsActive = true;
            db.SaveChanges();
            return Redirect("~/TimeSeries/GetTimeSeriesAdmin");
        }

        
    }
}

vkrS/vkrS/Controllers/ImageController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using vkrS.Models;
using System.Data.Entity;

namespace vkrS.Controllers
{
    public class ImageController : Controller
    {
        private VKRDbContext db = new VKRDbContext();

        // GET: Image
        public ActionResult GetImages()
        {
            var images = db.Images;
            ViewBag.Images = images;
            return View();
        }

        [HttpPost]
        public void AddImage(string imageInput, string description)
        {
            if (imageInput != null)
            {
                db.Images.Add(new Image { ImageId = Guid.NewGuid(), Link = imageInput });
                db.SaveChanges();
            }
        }
    }
}

vkrS/vkrS/Views/Home/Index.cshtml
@*@Scripts.Render("~/scripts/jquery-1.7.1.js")*@
@*@Scripts.Render("~/scripts/jquery.unobtrusive-ajax.js")*@
<script src="https://ajax.googleapis.com/ajax/libs/jquery/2.2.0/jquery.min.js"></script>
@Styles.Render("~/Content/css")

<form method="post" action="~/Home/Login" class="text-center">
    <h1 class="h3">Войти</h1>
    <input type="text" name="login" id="login" class="center-block form-control" required autofocus placeholder="Логин" />
    <input type="text" style = "margin-top: 0.5rem" name="password" id="password" class="center-block form-control" required autofocus placeholder="Пароль" />
    <button class="btn btn-primary btn-lg" style = "margin-top: 0.5rem" id="signIn">Войти</button>

</form>
<div class="text-center">
    @Html.ActionLink("Методы", "GetImages", "Image", null, new { @class = "btn btn-danger btn-lg ", @style = "margin-top: 0.5rem" })
</div>
<div id="tableBlock"></div>

@*@Html.DropDownList("ImageId", ViewBag.Images as SelectList)
@Html.DropDownList("TimeSeriesId", ViewBag.TimeSeries as SelectList)

<form id="imageUpload" @*action="@Url.Action("AddImage")" method="POST" enctype="multipart/form-data">
    <input id="imageInput" name="imageInput" type="text" />
    <input type="button" value="Upload image" id="btnImageUpload" onclick="AddImage()" />
</form>
<input type="button" value="Start" id="btnStart" onclick="Start()" />*@

@*<script type="text/javascript">
    $(document).ready(function () {
        GetAllTimeSeries();
    });

    //// Получение всех рядов по ajax-запросу
    //function GetAllTimeSeries() {
    //    $("#createBlock").css('display', 'block');
    //    //$("#editBlock").css('display', 'none');
    //    $.ajax({
    //        url: '/TimeSeries/GetTimeSeries',
    //        type: 'GET',
    //        dataType: 'json',
    //        success: function (data) {
    //            WriteResponse(data);
    //        },
    //        error: function (data) {
    //            alert('error' + data);
    //        }
    //    });
    //}

    //// вывод полученных данных на экран
    //function WriteResponse(ts) {
    //    var strResult = "<table><th>дабл</th><th>путь</th>";
    //    $.each(ts, function (index, t) {
    //        strResult += "<tr><td>" + t.IsDouble + "</td><td> " + t.Path + "</td></tr>";
    //    });
    //    strResult += "</table>";
    //    $("#tableBlock").html(strResult);
    //}

    function AddImage() {
        $.ajax({
            url: '@Url.Action("AddImage")',
            type: 'POST',
            data: JSON.stringify({ 'imageInput': $("#imageInput").val() }),
            contentType: "application/json;charset=utf-8",
            success: function (data) {
                GetAllTimeSeries();
                $("#imageInput").val('');
            },
            error: function () {
                alert('error');
            }
        });
    }

    function Start() {
        //debugger
        $.ajax({
            url: '@Url.Action("Start")',
            type: 'POST',
            data: JSON.stringify({ 'imageInput': $("#ImageId").val(), 'ts': $("#TimeSeriesId").val()}),
            contentType: "application/json;charset=utf-8",
            success: function (data) {
                GetAllTimeSeries();
            },
            error: function () {
                alert('error');
            }
        });
    }

</script>*@